### ISSUE TITLE
about patch_size

### ISSUE THREAD

**Issue by AdamKingsley** [guptapraful/niqe#1]
My evaluate images was under 192*192
Can I justify the patch_size smaller?
Does the patch size parameter is corresponsed to niqe_image_params.mat, so that the  patch size must be set as 96?

**Comment by guptapraful** [comment]
Although using different sized patches will not throw any error, I recommend using patch size = 96 for the best results as is used for the model generation ("niqe_image_params.mat") using pristine images.
